---
title: "Your Informative Title Here"
subtitle: "Case Study 2" 
author:
  - name: "Radiah Khan"
  - name: "Catherine Weeks" 
  - name: "Mercer Mercer"
  - name : "Nafisa Mohammad"
date: November 14
format: 
  pdf:
    geometry: 
      - left=1in
      - right=1in
      - top=1in
      - bottom=1in
execute: 
  echo: true
  message: false
  warning: false
---
```{r}
library(tidyverse)
library(ggplot2)
library(broom)
```
```{r, include=FALSE}
library(Sleuth2)
wages <- Sleuth2::ex1029
wages
```
```{r}
#no na values
sum(is.na(wages))
colSums(is.na(wages))
```
```{r} 
#EDA Potential 
# - (Wage and Race)
# - (Wage by regions)
# Have a combined plot on that if needed for the research question
#Need input on the EDA
```
```{r}
# Wrangling the data
#Average wage in each regions by race
wages_region_avg_wage <- wages |>
  select(Wage, Black, Region) |>
  group_by(Region, Black) |>
  summarise(avg_wage_region = mean(Wage, na.rm = TRUE))|>
  ungroup()
wages_region_avg_wage
```
```{r}
#Just has the experience group
wages_exp_group <- wages |>
  mutate(exp_group = case_when(
    Experience < 11 ~ "0–10",
    Experience < 21 ~ "11–20",
    Experience < 31 ~ "21-30",
    Experience < 41 ~ "31-40",
    Experience < 51 ~ "41-50",
    TRUE     ~ "50+"
  ))
wages_exp_group
  
```
```{r}
#Exp group + region
wages_exp_group_region <- wages_exp_group |>
  group_by(Region, Black, exp_group) |>
  summarise(avg_wage_region = mean(Wage, na.rm = TRUE))|>
  ungroup()
wages_exp_group_region
  
```

```{r}
unique(wages$Experience)

```


```{r}
#factoring the categorical variables in the wage data set
wages$Black <- factor(wages$Black)
wages$Region <- factor(wages$Region)

#setting the new reference level
wages$Black <- relevel(wages$Black, ref = "No")

```


```{r}
#MLM model
mlm_model_untransformed <- lm(Wage ~ Education  + Experience + Black * Region, data = wages)
summary(mlm_model)
```


```{r}
# Checking Linearity and Equal Variance
ggplot(mlm_model_untransformed |> augment(), aes(x = .fitted, y = .resid))+
  geom_point()+
  geom_hline(yintercept = 0, col = "red")+
  labs(title = "Scatterplot for residuals values in correlation to Fitted Values",
       x = "Fitted Results",
       y = "Residuals")
```

```{r}
# Checking for the normality condition
mlm_model_untransformed |>
  augment() |> ggplot(aes(sample = .resid)) + geom_qq() +
  geom_qq_line() +
  labs(title = "Scatterplot to display the Normaility ", x = "Quantilies", y = "Sample Outcomes")
```



```{r}
#MLM model with log scaled y axis
mlm_model <- lm(log(Wage) ~ Education  + Experience + Black * Region, data = wages)
summary(mlm_model)
```


```{r}
# Checking Linearity and Equal Variance
ggplot(mlm_model |> augment(), aes(x = .fitted, y = .resid))+
  geom_point()+
  geom_hline(yintercept = 0, col = "red")+
  labs(title = "Scatterplot for residuals values in correlation to Fitted Values",
       x = "Fitted Results",
       y = "Residuals")
```

```{r}
# Checking for the normality condition
mlm_model |>
  augment() |> ggplot(aes(sample = .resid)) + geom_qq() +
  geom_qq_line() +
  labs(title = "Scatterplot to display the Normaility ", x = "Quantilies", y = "Sample Outcomes")
```

```{r}
wages_reduced_model <- lm(log(Wage) ~ Education + Experience + Black + Region, data = wages)
summary(wages_reduced_model)
```


```{r}

anova(wages_reduced_model,mlm_model)

```



```{r}
#creating new labels for the facet wrapped variables 
graph.labels <- c("Yes"="Black","No" = "Non-Black")

#plotting a graph exploring Avg pay by region faceted by race
wages_region_avg_wage |> ggplot(aes(x=avg_wage_region, y = Region, fill = Black)) +geom_col()+ facet_grid(~Black,labeller = labeller(Black = graph.labels) )+coord_flip() +labs(title = "Average Pay in Each USA Region by Race", x= "Average Weekly Wage")+ theme_bw()
```



```{r}
library(knitr)
#Saving summary table of wages data
wages_summary <-summary(wages)

#printing the summary table created above with captions.
kable(wages_summary, 
      caption = "Summary of Wages")


```


